### ISSUE TITLE
slightly simpler BaseToDec

### ISSUE THREAD

**Issue by rjpgt** [joncalhoun/algorithmswithgo.com#2]
Here is a slightly simpler BaseToDec:
```
import "strings"

func BaseToDec(value string, base int) int {
	digits := "0123456789ABCDEF"
	dec := 0
	for _, chr := range value {
		dec = base*dec + strings.Index(digits, string(chr))
	}
	return dec
}
```

**Comment by joncalhoun** [comment]
Thanks for submitting this! I love seeing people go beyond what we do in the course and trying alternative approaches. 

While I definitely agree that your solution is shorter, I opted to go the route I did in the course because I felt there was value in seeing how you find the index of each character as well as explicitly walking through the algorithm much like you would if doing the conversion by hand. Maybe at some point in the future I will figure out a good way to also show off alternative implementations, but right now I don't really have one.

**Comment by rjpgt** [comment]
An alternative to FindTwoThatSum:
```
func FindTwoThatSum(numbers []int, sum int) (int, int) {
	for i := 0; i < len(numbers)-1; i++ {
		for j := i + 1; j < len(numbers); j++ {
			if numbers[i]+numbers[j] == sum {
				return i, j
			}
		}
	}
	return -1, -1
}
```
